# Generated by Django 2.2.1 on 2019-05-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='symbol',
            new_name='symbolCode',
        ),
    ]
